### Metody numeryczne 1 - Lista 3

#### Zadanie 1:

Rozwiąż, bez używania komputera, układ równań $Ax=b$ metodą eliminacji Gaussa dla

$$A=\begin{pmatrix}-1 & 1 & -4\\2 & 2 & 0\\3 & 3 & 2\end{pmatrix}\quad\text{i}\quad b=\begin{pmatrix}0 \\1\\0.5\end{pmatrix}\,. $$


#### Rozwiązanie - na osobnej kartce

#### Zadanie 2:
Korzystając z rozkładu LU macierzy A rozwiąż układ równań $LUx=b$ (bez używania komputera) dla

$$L=\begin{pmatrix}1 & 0 & 0\\3/2 & 1 & 0\\1/2 & 11/13 & 1\end{pmatrix}\,,\quad U=\begin{pmatrix}2 & -3 & -1\\0 & 13/2 & -7/2\\0 & 0 & 32/13\end{pmatrix}\quad\text{i}\quad b=\begin{pmatrix}1 \\-1\\2\end{pmatrix}\,. $$

#### Rozwiązanie - na osobnej kartce

#### Zadanie 3:

Rozwiąż układ równań $Ax=b$ dla

$$A=\begin{pmatrix}0 & 0 & 2 & 1 & 2\\ 0& 1 &0 &2 &-1\\ 1 & 2 & 0 &-2 &0\\ 0 & 0 &0 &-1 &1 \\ 0 &1  &-1 &1 &-1 \end{pmatrix}\quad\text{i}\quad b=\begin{pmatrix}1 \\1\\-4\\-2\\-1\end{pmatrix}\,. $$

wykorzystując *linalg.solve* z modułu *scipy*

#### Rozwiązanie:

In [2]:
import numpy as np
# Mateusz Wójcicki ISSP sem 3

# Building arrays
A = np.array([[0, 0, 2, 1, 2], [0, 1, 0, 2, -1], [1, 2, 0, -2, 0], [0, 0, 0, -1, 1], [0, 1, -1, 1, -1]])
b = np.array([1, 1, -4, -2, -1])

# Solving equations using numpy method
x = np.linalg.solve(A, b)

print("Result: \n", x)

Result: 
 [ 2. -2.  1.  1. -1.]


#### Zadanie 4:

Napisz program do eliminacji Gaussa i użyj go do ponownego rozwiązania zadań 1 ‐ 4 z tej listy

#### Rozwiązanie:

In [59]:
# Mateusz Wójcicki ISSP sem 3 20:10

# Zad 1
Z1 = [[-1, 1, -4], [2, 2, 0], [3, 3, 2]]
Z1b = [[0], [1], [0.5]]


# Zad 2
LU = [[2, -3, -1], [3, 2, -5], [1, 4, -1]]
Z2b = [[1], [-1], [2]]


# Zad 3
Z3 = [[0, 0, 2, 1, 2], [0, 1, 0, 2, -1], [1, 2, 0, -2, 0], [0, 0, 0, -1, 1], [0, 1, -1, 1, -1]]
Z3b = [[1], [1], [-4], [-2], [-1]]
    


def Gauss(M, m):
    # M is matrix to remake and m is a vector that will be used to extend M matrix
    M_temp = M
    print("\nInitial matrix:\n", np.array(M_temp))
    

    for x in range(0, len(M)):
        M_temp[x].append(m[x][0])
        
    for k in range(0, len(M[0])-1):
        
        # Special condition that change rows when its important element=0
        X=0
        while M_temp[k][k]==0:
            if M_temp[k+X+1][k]!=0:
                temp = M_temp[k]
                M_temp[k] = M_temp[k+X+1]
                M_temp[k+X+1] = temp
                
            else:
                X+=1
            
            
            
        # Creates temporary row to add
        for i in range(1+k, len(M)): # Till penultimate row(iteration by rows) 
            Mrow_multi = []
            
            for j in range(0, len(M[i-1])):
                if M_temp[k][k]!=0: Mrow_multi.append(M_temp[k][j]*(-M_temp[i][k]/M_temp[k][k])) #+X
            
            
            for x in range(0, len(Mrow_multi)): # Adding to row reworked row of matrix
                M_temp[i][x] += Mrow_multi[x]


    print("\n\nReady matrix:\n", np.array(M_temp))
    
    # Creating additional list to solve equations results and deleting addition elements in extended matrix
    extra_list = []
    length = len(M_temp)
    for x in range(0, length):
        extra_list.append(M_temp[x][length])
        M_temp[x].pop(length)

    print("\nReady matrix to solve:", np.array(M_temp), "\nExtra column:", np.array(extra_list), sep="\n")

    # Solving equations
    results = np.linalg.solve(M_temp, extra_list)
    
    
    # Printing results
    print("\n\nResults:")
    for x in range(0, length):
        print(f"x{x+1} = {results[x]}")

    print("\n"*3)
    


            

Gauss(Z1, Z1b)
Gauss(LU, Z2b)
Gauss(Z3, Z3b)



Initial matrix:
 [[-1  1 -4]
 [ 2  2  0]
 [ 3  3  2]]


Ready matrix:
 [[-1.  1. -4.  0.]
 [ 0.  4. -8.  1.]
 [ 0.  0.  2. -1.]]

Ready matrix to solve:
[[-1.  1. -4.]
 [ 0.  4. -8.]
 [ 0.  0.  2.]]

Extra column:
[ 0.  1. -1.]


Results:
x1 = 1.25
x2 = -0.75
x3 = -0.5





Initial matrix:
 [[ 2 -3 -1]
 [ 3  2 -5]
 [ 1  4 -1]]


Ready matrix:
 [[ 2.         -3.         -1.          1.        ]
 [ 0.          6.5        -3.5        -2.5       ]
 [ 0.          0.          2.46153846  3.61538462]]

Ready matrix to solve:
[[ 2.         -3.         -1.        ]
 [ 0.          6.5        -3.5       ]
 [ 0.          0.          2.46153846]]

Extra column:
[ 1.         -2.5         3.61538462]


Results:
x1 = 1.84375
x2 = 0.40625
x3 = 1.46875





Initial matrix:
 [[ 0  0  2  1  2]
 [ 0  1  0  2 -1]
 [ 1  2  0 -2  0]
 [ 0  0  0 -1  1]
 [ 0  1 -1  1 -1]]


Ready matrix:
 [[ 1.   2.   0.  -2.   0.  -4. ]
 [ 0.   1.   0.   2.  -1.   1. ]
 [ 0.   0.   2.   1.   2.   1. ]
 [ 0.   0.   0.  -1.   1.

#### Zadanie 5:

Oblicz normę i wskaźnik uwarunkowania macierzy Hilberta dla n=5, 10 i 20.

#### Rozwiązanie:

In [84]:
# Mateusz Wójcicki ISSP sem3

# Function to create Hilbert's matrix using py lists from Lista_1_MN
def Hilbert_creator(r0, rn):
    h = []
    h_row = []
    for i in range(r0, rn):
        for k in range(r0, rn):
            h_row.append(1/(i+k+1))
        h.append(h_row)
        h_row = []
    return h

# Hilbert's matrices
h2 = np.array(Hilbert_creator(0, 2))
h5 = np.array(Hilbert_creator(0, 5))
h10 = np.array(Hilbert_creator(0, 10))
h20 = np.array(Hilbert_creator(0, 20))

# Inversed
inv_h2 = np.array(np.linalg.inv(h2))
inv_h5 = np.array(np.linalg.inv(h5))
inv_h10 = np.array(np.linalg.inv(h10))
inv_h20 = np.array(np.linalg.inv(h20))

# cond of matrix H2 is norm(H2)*norm(H2^-1)

# Printing results
print("\n2x2 Hilbert's array:", np.array(h2), "\n||H2||:", np.linalg.norm(h2, np.inf), "\n||H2^-1||:", 
      np.linalg.norm(inv_h2, np.inf), "\ncond(H2):", np.linalg.cond(h2, np.inf), sep="\n")

print("\n5x5 Hilbert's array:", np.array(h5), "\n||H5||:", np.linalg.norm(h5, np.inf), "\n||H5^-1||:", 
      np.linalg.norm(inv_h5, np.inf), "\ncond(H5):", np.linalg.cond(h5, np.inf), sep="\n")

print("\n10x10 Hilbert's array:", np.array(h10), "\n||H10||:", np.linalg.norm(h10, np.inf), "\n||H10^-1||:", 
      np.linalg.norm(inv_h10, np.inf), "\ncond(H10):", np.linalg.cond(h10, np.inf), sep="\n")

print("\n20x20 Hilbert's array:", np.array(h20), "\n||H20||:", np.linalg.norm(h20, np.inf), "\n||H20^-1||:", 
      np.linalg.norm(inv_h20, np.inf), "\ncond(H20):", np.linalg.cond(h20, np.inf), sep="\n")


2x2 Hilbert's array:
[[1.         0.5       ]
 [0.5        0.33333333]]

||H2||:
1.5

||H2^-1||:
18.000000000000007

cond(H2):
27.00000000000001

5x5 Hilbert's array:
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]

||H5||:
2.283333333333333

||H5^-1||:
413280.0000027866

cond(H5):
943656.0000063627

10x10 Hilbert's array:
[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1       ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909 0.08333333]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909