### Metody numeryczne 1 - Lista 8

#### Zadanie 1:

Oblicz wartości i wektory własne macierzy

$$\begin{pmatrix} -1& -4& 1\\
-1& -2& -5\\
5 & 4& 3\end{pmatrix}$$


#### Rozwiązanie:

In [1]:
# Mateusz Wójcicki ISSP sem 3

import numpy as np
from scipy.linalg import eig

# Definiowanie macierzy
A = np.array([[-1, -4, 1],
              [-1, -2, -5],
              [5, 4, 3]])

# Obliczanie wartości własnych i wektorów własnych
eigenvalues, eigenvectors = eig(A)

# Wyświetlanie wyników
print("Wartości własne:")
print(eigenvalues)

print("\nWektory własne:")
print(eigenvectors)

Wartości własne:
[ 4.+0.j -2.+4.j -2.-4.j]

Wektory własne:
[[-5.77350269e-01+0.00000000e+00j  5.77350269e-01+0.00000000e+00j
   5.77350269e-01-0.00000000e+00j]
 [ 5.77350269e-01+0.00000000e+00j -5.78218248e-16-5.77350269e-01j
  -5.78218248e-16+5.77350269e-01j]
 [-5.77350269e-01+0.00000000e+00j -5.77350269e-01-5.39355242e-16j
  -5.77350269e-01+5.39355242e-16j]]


#### Zadanie 2:

Korzystając z modułu *Scipy* oblicz wszystkie wartości własne i wektory własne macierzy Hilberta $6\times6$.

#### Rozwiązanie:

In [2]:
import numpy as np
from scipy.linalg import hilbert, eig

# Generowanie macierzy Hilberta 6x6
hilbert_matrix = hilbert(6)

# Obliczenie wartości własnych i wektorów własnych
eigenvalues, eigenvectors = eig(hilbert_matrix)

# Wyświetlenie wyników
print("Wartości własne:")
print(eigenvalues)

print("\nWektory własne:")
print(eigenvectors)


Wartości własne:
[1.61889986e+00+0.j 2.42360871e-01+0.j 1.63215213e-02+0.j
 6.15748354e-04+0.j 1.25707571e-05+0.j 1.08279948e-07+0.j]

Wektory własne:
[[-0.74871922 -0.61454483  0.24032537 -0.06222659 -0.01114432 -0.00124819]
 [-0.4407175   0.21108248 -0.69765138  0.49083921  0.17973276  0.03560664]
 [-0.32069687  0.36589361 -0.23138937 -0.53547692 -0.60421221 -0.24067908]
 [-0.25431139  0.39470678  0.13286316 -0.41703769  0.44357472  0.62546039]
 [-0.21153084  0.38819043  0.36271492  0.04703402  0.44153664 -0.6898072 ]
 [-0.18144298  0.37069591  0.50276287  0.54068156 -0.45911482  0.27160545]]


#### Zadanie 3:

Oblicz trzy najmniejsze wartości własne i odpowiadające im wektory własne macierzy trójdiagonalnej $n\times n$

$$\begin{pmatrix} 2& -1& 0 & \dots & 0 \\
-1& 2& -1 & \dots & 0\\
0 & -1 & 2& \dots & 0\\
\vdots & \vdots & \ddots & \ddots & \vdots\\
0 & 0 & \dots -1 & 2
\end{pmatrix}$$


dla $n=10$ i $100$

#### Rozwiązanie:

In [3]:
import numpy as np
from scipy.linalg import eigh_tridiagonal

def tridiagonal_eigenproblem(n):
    
    # Tworzenie macierzy trójdiagonalnej
    diagonal = 2 * np.ones(n)
    off_diagonal = -1 * np.ones(n - 1)

    # Obliczenie wartości własnych i wektorów własnych
    eigenvalues, eigenvectors = eigh_tridiagonal(diagonal, off_diagonal, select='i', select_range=(0, 2))

    return eigenvalues, eigenvectors

# Dla n = 10
n_10_eigenvalues, n_10_eigenvectors = tridiagonal_eigenproblem(10)

print("Najmniejsze trzy wartości własne dla n = 10:")
print(n_10_eigenvalues)

# Dla n = 100
n_100_eigenvalues, n_100_eigenvectors = tridiagonal_eigenproblem(100)

print("\nNajmniejsze trzy wartości własne dla n = 100:")
print(n_100_eigenvalues)


Najmniejsze trzy wartości własne dla n = 10:
[0.08101405 0.31749293 0.69027853]

Najmniejsze trzy wartości własne dla n = 100:
[0.00096744 0.00386881 0.0087013 ]


#### Zadanie 4:

Znajdź cztery najmniejsze wartości własne kwantowego oscylatora anharmonicznego, którego równanie Schrodingera ma postać

$$-\frac{1}{2}\frac{d^2\psi}{dx^2}+\left(\frac{x^2}{2}+\lambda x^4\right)\psi(x)=E\psi(x)$$

z następującymi warunkami brzegowymi $y(0) = 0$ i $y(\pi)=0$. 


**Wskazówka:** Wprowadzając siatkę równoodległych punktów
$$x_i=-a+ih,\quad i=0,1,\dots\,,m;\quad h=\frac{2a}{m}$$
i zastępując drugą pochodną $\psi$ w $x_i$ przybliżeniem różnicy centralnej

$$\frac{d^2\psi}{dx^2}\approx\frac{\psi(x_{i-1})-2\psi(x_i)+\psi(x_{i+1})}{h^2}=\frac{\psi_{i-1}-2\psi_i+\psi_{i+1}}{h^2}$$

oraz zakładając, że $\psi_0=\psi_m=0$ możemy równanie Schrodingera zapisać w postaci macierzowej

$$\boldsymbol{H\psi}=E\boldsymbol{\psi}\,,$$

gdzie

$$\boldsymbol{\psi}=(\psi_1,\psi_2,\dots,\psi_{m-1})^T$$

i

$$\boldsymbol{H}=\begin{pmatrix} d_1& g& 0 & \dots & 0 \\
g& d_2& g & \dots & 0\\
0 & g & d_3& \dots & 0\\
\vdots & \vdots & \ddots & \ddots & \vdots\\
0 & 0 & \dots & g & d_{m-1}
\end{pmatrix}$$

z

$$g=-\frac{1}{2h^2}\,,\quad d_i=\frac{1}{h^2}+\frac{x_{i}^2}{2}+\lambda x_i^4$$

Oblicz wartości własne trójdiagonalnej macierzy $\boldsymbol{H}$ dla $\lambda=0.2$, $a=4.6$, $m=100$ i $1000$. Wykreśl 4 funkcje falowe (wektory własne $\boldsymbol{H}$) dla czterech najmniejszych energii własnych.

#### Rozwiązanie: